[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8088

; Включаем поддержку WebSocket
enablestatic=yes
redirect=/static/config /var/lib/asterisk/static-http

; Включаем TLS (опционально, для wss://)
; tlsenable=yes
; tlsbindaddr=0.0.0.0:8089
; tlscertfile=/etc/asterisk/keys/asterisk.pem
; tlsprivatekey=/etc/asterisk/keys/asterisk.key
